/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.student_management;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class StudentBoard extends javax.swing.JFrame {

    ListStudent listStudent=new ListStudent();
    DefaultTableModel defaultTableModel;
    ListScore listScore=new ListScore();
    /**
     * Creates new form StudentBoard
     */
    public StudentBoard() {
        listScore.insert();
        listStudent.insert();
        initComponents();
        defaultTableModel=(DefaultTableModel)StudentTable.getModel();
        display();
    }

    private void display() {
        if(listStudent.getSize()!=0)
        {
            for(int i=0;i<listStudent.getSize();i++)
            {
                showTable((i+1),listStudent.getStudentAtIndex(i));
            }
        }
    }
    public String getGenderToString(boolean x)
    {
        if(x==true)
        {
            return "Nam";
        }
        return "Nu";
    }
       public String getAverageScore(String idStudent)
    {
        int soTin=listScore.getSOTinOfAStudent(idStudent);
        if(soTin!=0){
            return String.valueOf(listScore.getAverageScoreOfAStudent(idStudent));
        }
        return "";
    }
    public void showTable(int i,Student st)
    {
        defaultTableModel.addRow(new Object[]{
            i,st.getId(),st.getName(),getGenderToString(st.isGender()),st.getAddress(),st.getPhoneNumber(),st.getEmail(),getAverageScore(st.getId())
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        insertScoreButton = new javax.swing.JButton();
        updateScoreButton = new javax.swing.JButton();
        deleteScoreButton = new javax.swing.JButton();
        searchScoreButton = new javax.swing.JButton();
        editScoreButton = new javax.swing.JButton();
        resetScoreButton = new javax.swing.JButton();
        deleteAllScoreButton = new javax.swing.JButton();
        sortByScoreButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        idStudentLabel = new javax.swing.JLabel();
        idStudentTextField = new javax.swing.JTextField();
        nameStudentLabel = new javax.swing.JLabel();
        idStudentTextField1 = new javax.swing.JTextField();
        genderStudentLabel = new javax.swing.JLabel();
        nameStudentLabel1 = new javax.swing.JLabel();
        addressStudentTextField = new javax.swing.JTextField();
        maleRadioButton = new javax.swing.JRadioButton();
        femaleRadioButton = new javax.swing.JRadioButton();
        phoneNumberTextField = new javax.swing.JTextField();
        phoneNUmberLabel = new javax.swing.JLabel();
        emailStudentTextField = new javax.swing.JTextField();
        emailStudentLabel = new javax.swing.JLabel();
        searchStudentButton = new javax.swing.JButton();
        insertStudentButton = new javax.swing.JButton();
        deleteStudentButton = new javax.swing.JButton();
        resetStudentButton = new javax.swing.JButton();
        editStudentButton = new javax.swing.JButton();
        deleteAllStudentButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        StudentTable = new javax.swing.JTable();

        insertScoreButton.setText("Insert");

        updateScoreButton.setText("Update");

        deleteScoreButton.setText("Delete");
        deleteScoreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteScoreButtonActionPerformed(evt);
            }
        });

        searchScoreButton.setText("Search");
        searchScoreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchScoreButtonActionPerformed(evt);
            }
        });

        editScoreButton.setText("Edit");
        editScoreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editScoreButtonActionPerformed(evt);
            }
        });

        resetScoreButton.setText("Reset");

        deleteAllScoreButton.setText("Delete all");

        sortByScoreButton.setText("Sort By Score");
        sortByScoreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortByScoreButtonActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("Student List");

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        idStudentLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        idStudentLabel.setText("ID");

        nameStudentLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameStudentLabel.setText("Name");

        genderStudentLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        genderStudentLabel.setText("gender");

        nameStudentLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameStudentLabel1.setText("Address");

        maleRadioButton.setText("Nam");

        femaleRadioButton.setText("Nữ");

        phoneNUmberLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        phoneNUmberLabel.setText("Phone Number");

        emailStudentLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emailStudentLabel.setText("Email");

        searchStudentButton.setText("Search");

        insertStudentButton.setText("Insert");

        deleteStudentButton.setText("Delete");

        resetStudentButton.setText("Reset");
        resetStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetStudentButtonActionPerformed(evt);
            }
        });

        editStudentButton.setText("Edit");

        deleteAllStudentButton.setText("Delete all");
        deleteAllStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAllStudentButtonActionPerformed(evt);
            }
        });

        StudentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Stt", "ID", "Name", "Gender", "Address", "Phone Number", "Email", "Score"
            }
        ));
        jScrollPane1.setViewportView(StudentTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(237, 237, 237)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(idStudentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nameStudentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idStudentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(idStudentTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(genderStudentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(maleRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(femaleRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(phoneNUmberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(phoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nameStudentLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(addressStudentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(emailStudentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(searchStudentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emailStudentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(editStudentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(89, 89, 89))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(insertStudentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(resetStudentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(150, 150, 150)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deleteStudentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteAllStudentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 859, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(idStudentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idStudentTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(nameStudentLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addressStudentTextField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(idStudentTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(nameStudentLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(phoneNUmberLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(phoneNumberTextField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(genderStudentLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                        .addComponent(maleRadioButton)
                        .addComponent(femaleRadioButton))
                    .addComponent(emailStudentLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(emailStudentTextField))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchStudentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteStudentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insertStudentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resetStudentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteAllStudentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editStudentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(149, 149, 149))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.toBack();
        View v=new View();
        v.setVisible(true);
        this.dispose();
        v.toFront();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void deleteScoreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteScoreButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteScoreButtonActionPerformed

    private void searchScoreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchScoreButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchScoreButtonActionPerformed

    private void editScoreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editScoreButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editScoreButtonActionPerformed

    private void sortByScoreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortByScoreButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sortByScoreButtonActionPerformed

    private void resetStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetStudentButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resetStudentButtonActionPerformed

    private void deleteAllStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAllStudentButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteAllStudentButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable StudentTable;
    private javax.swing.JTextField addressStudentTextField;
    private javax.swing.JButton deleteAllScoreButton;
    private javax.swing.JButton deleteAllStudentButton;
    private javax.swing.JButton deleteScoreButton;
    private javax.swing.JButton deleteStudentButton;
    private javax.swing.JButton editScoreButton;
    private javax.swing.JButton editStudentButton;
    private javax.swing.JLabel emailStudentLabel;
    private javax.swing.JTextField emailStudentTextField;
    private javax.swing.JRadioButton femaleRadioButton;
    private javax.swing.JLabel genderStudentLabel;
    private javax.swing.JLabel idStudentLabel;
    private javax.swing.JTextField idStudentTextField;
    private javax.swing.JTextField idStudentTextField1;
    private javax.swing.JButton insertScoreButton;
    private javax.swing.JButton insertStudentButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton maleRadioButton;
    private javax.swing.JLabel nameStudentLabel;
    private javax.swing.JLabel nameStudentLabel1;
    private javax.swing.JLabel phoneNUmberLabel;
    private javax.swing.JTextField phoneNumberTextField;
    private javax.swing.JButton resetScoreButton;
    private javax.swing.JButton resetStudentButton;
    private javax.swing.JButton searchScoreButton;
    private javax.swing.JButton searchStudentButton;
    private javax.swing.JButton sortByScoreButton;
    private javax.swing.JButton updateScoreButton;
    // End of variables declaration//GEN-END:variables

    
}
